version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/laravel
    test:
      override:
        - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
        - phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml test
    steps:
      - checkout
      - run: sudo apt-get install jpegoptim
      - run: sudo apt-get install optipng
      - run: sudo apt-get install pngquant
      - run: sudo apt-get install -y libpng-dev
      - run:
          name: Install PHP Extensions
          command: sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev && sudo docker-php-ext-configure gd exif --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && sudo docker-php-ext-install -j$(nproc) gd
      - run: sudo apt-get install gifsicle
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: touch database/database.sqlite
      - run: php artisan migrate --env=testing --database=sqlite --force
      - run: ./vendor/bin/phpunit